VERSION: 2
NETWORK:
  META_ARCH: "GeneralClsModel"
  NUM_CLASSES: 4
  BACKBONE_ARCH: "resnest101"
  BNNECK: False
  FC_DROPOUT: 0.0
  LABEL_SMOOTHING: 0.1
  PRETRAINED: True
SOLVER:
  MAX_ITER: 32000
  CHECKPOINT_PERIOD: 2000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.004444
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 1000
  WARMUP_METHOD: "linear"
DATA:
  TRAIN_SIZE: [224, 224]
  VALID_SIZE: [224, 224]
  TEST_SIZE: [224, 224]
  BATCHSIZE: 16
  NUM_WORKERS: 8
  DATASETS:
    TRAIN_DIR: ""
    VALID_DIR: ""
    TEST_DIR: ""
